accessing
addError: error for: anObject
	(self errorsFor: anObject) add: error